-- Create Presentation Metrics table in Redshift
-- This table stores the metrics generated by the generate_metrics_job.py

CREATE TABLE IF NOT EXISTS presentation.presentation_metrics (
    metrics_date DATE PRIMARY KEY,
    total_listings INTEGER,
    active_listings INTEGER,
    avg_price FLOAT,
    min_price FLOAT,
    max_price FLOAT,
    avg_days_listed FLOAT,
    total_viewings INTEGER,
    total_wishlisted INTEGER,
    total_users INTEGER,
    total_timed_viewings INTEGER,
    avg_viewing_duration FLOAT,
    total_bookings INTEGER,
    confirmed_bookings INTEGER,
    avg_booking_value FLOAT,
    total_booking_value FLOAT,
    avg_booking_duration FLOAT,
    booking_conversion_rate FLOAT,
    wishlist_rate FLOAT,
    avg_viewings_per_listing FLOAT,
    generated_at TIMESTAMP,
    etl_inserted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create distribution and sort keys for performance
-- ALTER TABLE presentation.presentation_metrics ALTER DISTSTYLE ALL;
-- ALTER TABLE presentation.presentation_metrics ALTER SORTKEY (metrics_date);
